name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build_os: [ ubuntu-latest ]
        host_os: [ linux, nixos, darwin ]
        host_arch: [ x86_64, aarch64 ]

    runs-on: ${{ matrix.build_os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Run Build (${{ matrix.host_arch }}-${{ matrix.host_os }})
        run: nix -L build .#app/${{ matrix.host_os }}/${{ matrix.host_arch }}

  build-wasm:
    name: build (ubuntu-latest, freestanding, wasm32)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Run Build (wasm32-freestanding)
        run: nix -L build .#app/wasm

  build-windows:
    name: build (ubuntu-latest, windows, x86_64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Run Build (Windows x86_64)
        run: nix -L build .#app/windows/x86_64

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-windows-x86_64
          path: ./result/bin/
