name: CI

on:
  push:
    branches: [ "main", "darwin" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Run Build (Linux x86_64)
        run: nix -L build .#game/linux/x86_64
        if: matrix.os == 'ubuntu-latest'

      - name: Run Build (NixOS x86_64)
        run: nix -L build .#game/nixos/x86_64
        if: matrix.os == 'ubuntu-latest'

      - name: Run Build (Windows x86_64)
        run: nix -L build .#game/windows/x86_64
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: game-windows-x86_64
          path: ./result/bin/
        if: matrix.os == 'ubuntu-latest'

      - name: Run Build (macOS x86_64)
        run: nix -L build .#game/darwin/x86_64
        if: matrix.os == 'macos-latest'

